### ISSUE TITLE
editable drop-down for proxy-url

### ISSUE THREAD

**Issue by KaiPUecker** [Neofonie/a11y#43]
As user i want to have an editable drop-down rather then an input, to either enter my URL by myself or to select a predefined URL.

AC:

- [ ] Instead of an input-field there should be a select 
- [ ] Select should be editable
- [ ] Predefined values should be:
- [ ]   http://localhost:8080/
- [ ]   https://a11y.neofonie.de:8443/

Optional:
maybe the selected value could be stored in localStorage for convenience

**Comment by dutscher** [comment]
ja hatte ich auch schon überlegt, aber im bezug auf schnelles debugging ist das input erstmal die bessere wahl. localhost ist bisher das einzige was geht und wenn der proxy dann fertig ist kommt das feld da eh wieder weg.

**Comment by dutscher** [comment]
brauch es nicht mehr
